pipeline {
    agent any
    stages {
        stage('Recuperation du code') {
            steps {
                git branch: 'main', url: 'https://github.com/CyliaHammadi/futurekawa-mspr.git'
            }
        }
        stage('Installation des dependances') {
            steps {
                bat 'pip install -r backend-pays/requirements.txt'
            }
        }
        stage('Tests automatiques') {
            steps {
                bat 'cd backend-pays && python -m pytest tests/ -v'
            }
        }
    }
    post {
        success {
            echo 'Tous les 15 tests sont passes !'
        }
        failure {
            echo 'Des tests ont echoue !'
        }
    }
}